import { Inter } from "next/font/google";
import Header from "@/Component/Header";
import Foot from "@/Component/Foot";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Foot />
      </body>
    </html>
  );
}
