import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../Component/Header";
import Foot from "../Component/Foot";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Foot />
      </body>
    </html>
  );
}
